services:
  app:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app
    depends_on:
      - db
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE}
